[pytest]

markers =
    test_capitalize_positive: mark a test as positive
    test_capitalize_negative: mark a test as negative
    test_trim_positive: mark a test as positive
    test_trim_negative: mark a test as negative
    test_contains_positive: mark a test as positive
    test_contains_negative: mark a test as negative
    test_delete_symbol_positive: mark a test as positive
    test_delete_symbol_negative: mark a test as negative



#python_files= *abc.py
#python_functions= *sum*



